# Generated by Django 3.2 on 2021-05-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardarchive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCardSet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='set',
            field=models.ForeignKey(default='deleteme', on_delete=django.db.models.deletion.RESTRICT, to='cardarchive.pokemoncardset'),
            preserve_default=False,
        ),
    ]
